--[[ 
    script: Skin System & Clothe Shop
    author: SM Developer
    discord: https://discord.gg/ZbJP9wptwB
    ทางเราขอบคุณเป็นอย่างยิ่งที่ท่านได้สนับสนุนสินค้าของเรา
]]

Config = Config or {}

Config['translate'] = {
    enough_money = 'Your money not enough',

    ui_text = {
        cloth_shop = 'ร้านเปลี่ยนชุด',
        player_view = 'มุมมองตัวละคร',
        text_help1 = 'สามารถใช้การลูกกลิ้งที่เมาส์เพื่อหมุนมุมมองของตัวละครได้',
        text_help2 = 'สามารถ “กด X” เพื่อยกแขนของตัวละคร',
        cloth_fav = 'เพิ่มเครื่องแต่งกายเข้าตู้เสื้อผ้า',
        save = 'บันทึก',
        cloth_locker = 'ตู้เสื้อผ้าของคุณ',
        select = 'เลือก',
        cloth_cfm = 'ยืนยันการแต่งกาย',

        barber_shop = 'ร้านแต่งหน้า',
        barber_fav = 'เพิ่มเครื่องแต่งกายเข้าตู้เสื้อผ้า',
        barber_locker = 'ตู้เสื้อผ้าของคุณ',
        barber_cfm = 'ยืนยันการแต่งกาย',

        skin_menu_1 = 'เลือกลักษณะตัวละคร',
        skin_menu_2 = 'เลือกการแต่งกาย',
        skin_cfm = 'ยืนยันการแต่งกาย',

        mask_shop = 'ร้านหน้ากาก',
        mask_cfm = 'ยืนยันการแต่งกาย',

        locker_menu = 'ตู้เสื้อผ้าของคุณ',
        locker_cfm = 'ยืนยันการแต่งกาย',
    },

    cloth = {
        tshirt_1 = 'เสื้อด้านใน',
        torso_1 = 'เสื้อด้านนอก',
        decals_1 = 'สติกเกอร์',
        arms = 'แขนและถุงมือ',
        pants_1 = 'กางเกง',
        shoes_1 = 'รองเท้า',
        chain_1 = 'สร้อย',
        helmet_1 = 'หมวก',
        glasses_1 = 'แว่นตา',
        bags_1 = 'กระเป๋า',
        bproof_1 = 'เสื้อเกราะ',
        watches_1 = 'นาฬิกา',
        bracelets_1 = 'กำไลข้อมือ',

        color_texture = 'สี / ลาย',
    },
    skin = {
        sex = 'เพศ',
        eye_color = 'สีตา',
        eye_squint = 'เปลือกตา',
        face = 'หน้าตา',
        skin = 'สีผิว',
        mom = 'แม่',
        dad = 'พ่อ',
        face_md_weight = 'หน้าคล้าย แม่ - พ่อ',
        skin_md_weight = 'สีผิวคล้าย แม่ - พ่อ',
        chest_1 = 'รูปแบบ',
        chest_2 = 'ความเข้ม',
        chest_3 = 'สี',
        bodyb_1 = 'รูปแบบ',
        bodyb_2 = 'ความเข้ม',
        bodyb_3 = 'รูปแบบ 2',
        bodyb_4 = 'ความเข้ม',
        age_1 = 'รูปแบบ',
        age_2 = 'ความเข้ม',
        blemishes_1 = 'รูปแบบ',
        blemishes_2 = 'ความเข้ม',
        complexion_1 = 'รูปแบบ',
        complexion_2 = 'ความเข้ม',
        sun_1 = 'รูปแบบ',
        sun_2 = 'ความเข้ม',
        moles_1 = 'รูปแบบ',
        moles_2 = 'ความเข้ม',
        hair_1 = 'รูปแบบ',
        hair_2 = 'รูปแบบ 2',
        hair_color_1 = 'สีหลัก',
        hair_color_2 = 'สีรอง',
        eyebrows_1 = 'รูปแบบ',
        eyebrows_2 = 'ความเข้ม',
        eyebrows_3 = 'สีหลัก',
        eyebrows_4 = 'สีรอง',
        eyebrows_5 = 'ความสูง',
        eyebrows_6 = 'ความลึก',
        makeup_1 = 'รูปแบบ',
        makeup_2 = 'ความเข้ม',
        makeup_3 = 'สีหลัก',
        makeup_4 = 'สีรอง',
        lipstick_1 = 'รูปแบบ',
        lipstick_2 = 'ความเข้ม',
        lipstick_3 = 'สีหลัก',
        lipstick_4 = 'สีรอง',
        ears_1 = 'รูปแบบ',
        ears_2 = 'สี',
        blush_1 = 'รูปแบบ',
        blush_2 = 'ความเข้ม',
        blush_3 = 'สี',
        beard_1 = 'รูปแบบ',
        beard_2 = 'ความเข้ม',
        beard_3 = 'สีหลัก',
        beard_4 = 'สีรอง',
        mask_1 = 'รูปแบบ',
        mask_2 = 'สี',
        nose_1 = 'ความกว้างปีกจมูก',
        nose_2 = 'ตำแหน่งความสูงจมูก',
        nose_3 = 'ความโด่งปลายจมูก',
        nose_4 = 'ความโด่งสันจมูก',
        nose_5 = 'ความเชิดงอปลายจมูก',
        nose_6 = 'บิดจมูก',
        cheeks_1 = 'ความสูงต่ำของโหนก',
        cheeks_2 = 'ความของโหนก',
        cheeks_3 = 'ความกว้างขอแก้ม',
        lip_thickness = 'ความหน้าปาก',
        jaw_1 = 'ความกว้าง',
        jaw_2 = 'ความสูง',
        chin_1 = 'ความสูงคาง',
        chin_2 = 'ความยื่นคาง',
        chin_3 = 'ความเรียวคาง',
        chin_4 = 'หลุมที่คาง',
        neck_thickness = 'ความหนาของคอ',
    },

    skin_category = {
        sex = 'เพศ',
        eye = 'ดวงตา',
        shape = 'รูปร่าง',
        chest = 'ขนหน้าอก',
        bodyb = 'ตำหนิร่างกาย',
        wrinkles = 'ริ้วรอยความแก่',
        blemishes = 'ตำหนิที่หน้า',
        complexion = 'รอยช้ำที่หน้า',
        sun = 'ริ้วรอยที่หน้า',
        moles = 'กระที่หน้า',
        hair = 'ทรงผม',
        eyebrows = 'คิ้ว',
        makeup = 'เพ้นท์หน้า',
        lipstick = 'ลิปสติก',
        ears = 'ต่างหู',
        blush = 'บลัช',
        beard = 'หนวด',
        mask = 'หน้ากาก',
        nose = 'จมูก',
        cheeks = 'โหนกแก้ม',
        lip = 'ริมฝีปาก',
        jaw = 'กราม',
        chin = 'คาง',
    }

}