PlayerEnvs = {} PlayerEnvs.toStr = tostring

PlayerEnvs.showhudcomponent = true
PlayerEnvs.SpawnMod = true 
PlayerEnvs.HealRecharge = true 
PlayerEnvs.pointing = true


--[ * Weapon Drop Blocked | ปิดอาวุธดรอปในเซิฟทั้งหมด
PlayerEnvs.WeaponDropBlockedList = {
    PlayerEnvs.toStr(`PICKUP_AMMO_BULLET_MP`) ,
    PlayerEnvs.toStr(`PICKUP_AMMO_FIREWORK`) ,
    PlayerEnvs.toStr(`PICKUP_AMMO_FLAREGUN`) ,
    PlayerEnvs.toStr(`PICKUP_AMMO_GRENADELAUNCHER`),
    PlayerEnvs.toStr(`PICKUP_AMMO_GRENADELAUNCHER_MP`),
    PlayerEnvs.toStr(`PICKUP_AMMO_HOMINGLAUNCHER`),
    PlayerEnvs.toStr(`PICKUP_AMMO_MG`),
    PlayerEnvs.toStr(`PICKUP_AMMO_MINIGUN`),
    PlayerEnvs.toStr(`PICKUP_AMMO_MISSILE_MP`),
    PlayerEnvs.toStr(`PICKUP_AMMO_PISTOL`),
    PlayerEnvs.toStr(`PICKUP_AMMO_RIFLE`),
    PlayerEnvs.toStr(`PICKUP_AMMO_RPG`),
    PlayerEnvs.toStr(`PICKUP_AMMO_SHOTGUN`),
    PlayerEnvs.toStr(`PICKUP_AMMO_SMG`),
    PlayerEnvs.toStr(`PICKUP_AMMO_SNIPER`),
    PlayerEnvs.toStr(`PICKUP_ARMOUR_STANDARD`),
    PlayerEnvs.toStr(`PICKUP_CAMERA`),
    PlayerEnvs.toStr(`PICKUP_CUSTOM_SCRIPT`),
    PlayerEnvs.toStr(`PICKUP_GANG_ATTACK_MONEY`),
    PlayerEnvs.toStr(`PICKUP_HEALTH_SNACK`),
    PlayerEnvs.toStr(`PICKUP_HEALTH_STANDARD`),
    PlayerEnvs.toStr(`PICKUP_MONEY_CASE`),
    PlayerEnvs.toStr(`PICKUP_MONEY_DEP_BAG`),
    PlayerEnvs.toStr(`PICKUP_MONEY_MED_BAG`),
    PlayerEnvs.toStr(`PICKUP_MONEY_PAPER_BAG`),
    PlayerEnvs.toStr(`PICKUP_MONEY_PURSE`),
    PlayerEnvs.toStr(`PICKUP_MONEY_SECURITY_CASE`),
    PlayerEnvs.toStr(`PICKUP_MONEY_VARIABLE`),
    PlayerEnvs.toStr(`PICKUP_MONEY_WALLET`),
    PlayerEnvs.toStr(`PICKUP_PARACHUTE`),
    PlayerEnvs.toStr(`PICKUP_PORTABLE_CRATE_FIXED_INCAR`),
    PlayerEnvs.toStr(`PICKUP_PORTABLE_CRATE_UNFIXED`),
    PlayerEnvs.toStr(`PICKUP_PORTABLE_CRATE_UNFIXED_INCAR`),
    PlayerEnvs.toStr(`PICKUP_PORTABLE_CRATE_UNFIXED_INCAR_SMALL`),
    PlayerEnvs.toStr(`PICKUP_PORTABLE_CRATE_UNFIXED_LOW_GLOW`),
    PlayerEnvs.toStr(`PICKUP_PORTABLE_DLC_VEHICLE_PACKAGE`),
    PlayerEnvs.toStr(`PICKUP_PORTABLE_PACKAGE`),
    PlayerEnvs.toStr(`PICKUP_SUBMARINE`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_ARMOUR_STANDARD`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_CUSTOM_SCRIPT`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_CUSTOM_SCRIPT_LOW_GLOW`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_HEALTH_STANDARD`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_HEALTH_STANDARD_LOW_GLOW`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_MONEY_VARIABLE`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_WEAPON_APPISTOL`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_WEAPON_ASSAULTSMG`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_WEAPON_COMBATPISTOL`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_WEAPON_GRENADE`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_WEAPON_MICROSMG`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_WEAPON_MOLOTOV`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_WEAPON_PISTOL`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_WEAPON_PISTOL50`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_WEAPON_SAWNOFF`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_WEAPON_SMG`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_WEAPON_SMOKEGRENADE`),
    PlayerEnvs.toStr(`PICKUP_VEHICLE_WEAPON_STICKYBOMB`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_ADVANCEDRIFLE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_APPISTOL`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_ASSAULTRIFLE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_ASSAULTSHOTGUN`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_ASSAULTSMG`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_AUTOSHOTGUN`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_BAT`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_BATTLEAXE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_BOTTLE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_BULLPUPRIFLE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_BULLPUPSHOTGUN`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_CARBINERIFLE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_COMBATMG`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_COMBATPDW`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_COMBATPISTOL`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_COMPACTLAUNCHER`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_COMPACTRIFLE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_CROWBAR`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_DAGGER`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_DBSHOTGUN`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_FIREWORK`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_FLAREGUN`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_FLASHLIGHT`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_GRENADE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_GRENADELAUNCHER`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_GUSENBERG`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_GOLFCLUB`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_HAMMER`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_HATCHET`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_HEAVYPISTOL`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_HEAVYSHOTGUN`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_HEAVYSNIPER`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_HOMINGLAUNCHER`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_KNIFE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_KNUCKLE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_MACHETE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_MACHINEPISTOL`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_MARKSMANPISTOL`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_MARKSMANRIFLE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_MG`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_MICROSMG`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_MINIGUN`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_MINISMG`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_MOLOTOV`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_MUSKET`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_NIGHTSTICK`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_PETROLCAN`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_PIPEBOMB`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_PISTOL`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_PISTOL50`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_POOLCUE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_POOLCUE_PUNK`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_PROXMINE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_PUMPSHOTGUN`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_RAILGUN`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_REVOLVER`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_RPG`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_SAWNOFFSHOTGUN`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_SMG`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_SMOKEGRENADE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_SNIPERRIFLE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_SNSPISTOL`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_SPECIALCARBINE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_STICKYBOMB`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_STUNGUN`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_SWITCHBLADE`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_VINTAGEPISTOL`),
    PlayerEnvs.toStr(`PICKUP_WEAPON_WRENCH`), 
    PlayerEnvs.toStr(`PICKUP_WEAPON_RAYCARBINE`)
}


--[ * Player Crouch |  เปิดให้กด L-Ctrl เพื่อนั่งได้
PlayerEnvs.EnableCrouch = true


--[ * Player HandsUp | เปิดให้กด X เพื่อยกมือขึ้น ( Animation ยอมจำนน )
PlayerEnvs.EnableHandsUp = false

PlayerEnvs.ESX = {}
--[[ * Require ( ESX Framwork | ต้องการ ESX ) --]]
--[ * Player Vehicle Push | เปิดให้กด Shift + E เพื่อดันรถ
    PlayerEnvs.ESX.VehiclePush = true
--]


--[ * Player disable control on car | ลิสต์ปุ่มที่ปิดไม่ให้กดเมื่ออยู่บนรถ
PlayerEnvs.WhileCarBlockControl = {
    {1, 105} , --[ + Example DisableControlAction(1, 105) ]
    {1, 120} ,
    {0, 120} ,
    {1, 154} ,
    {0, 154} ,
    {1, 186} ,
    {0, 186} ,
    {1, 252} ,
    {0, 252} ,
    {1, 323} ,
    {0, 323} ,
    {1, 337} ,
    {0, 337} ,
    {1, 345} ,
    {0, 345} ,
    {1, 346} ,
    {0, 346} ,
    {1, 347} ,
    {0, 347} ,
    {1, 354} ,
    {0, 354} ,
    {0, 73}  ,
    {1, 73}  ,
    {0, 105},
    --{0,136},
    --{1,136},
    {0,37},
    {1,37},
    --{0,136},
    --{1,136},
}