-- ████╗   ██╗   ██████╗   ██████╗  ██████╗ ██╗  ██╗ ██████╗ ██╗     █████╗  ██████╗  ██████╗ ██████╗    ██╗ --
-- ██╔██╗  ██║ ██╔═════╝   ██╔══██╗ ██╔═══╝ ██║  ██║ ██╔═══╝ ██║    ██╔══██╗ ██╔══██╗ ██╔═══╝ ██╔══██╗   ██║ --
-- ██║╚██╗ ██║ ██║         ██║  ██║ █████╗  ██║  ██║ █████╗  ██║    ██║  ██║ ██████╔╝ █████╗  ██████╔╝   ██║ --
-- ██║ ╚██╗██║ ██║         ██║  ██║ ██╔══╝  ╚██╗██╔╝ ██╔══╝  ██║    ██║  ██║ ██╔═══╝  ██╔══╝  ██╔══██╗   ╚═╝ --
-- ██║  ╚████║ ╚═██████╗   ██████╔╝ ██████╗  ╚███╔╝  ██████╗ ██████╗╚█████╔╝ ██║      ██████╗ ██║  ██║   ██╗ --
-- ╚═╝   ╚═══╝   ╚═════╝   ╚═════╝  ╚═════╝   ╚══╝   ╚═════╝ ╚═════╝ ╚════╝  ╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝ --

-- Resources ที่ไม่ต้องการให้ Protect (ไม่แนะนำให้ใส่ Resource ที่มี Event ชื่อเดียวกับ Resource อื่น)
-- สำคัญ!!	หากใส่ชื่อ Resource ใดๆไว้ในนี้ PROTECT+ จะมองว่า Resource นั้นๆอยู่นอกเหนือการควบคุมของ PROTECT+ (บางอย่าง)
-- 			Resource ที่มีการ Trigger ข้ามไป Resource อื่นๆหรือเสก Weapon ต่างๆจะไม่ถูกมองเป็นโปรทั้งหมด
Config.IgnoredResources = {
	-- ใส่ชื่อทรัพยากรที่นี่

	-- DLL Resources
	'refuelingnozzle',
	'vMenu',

	-- Database
	'mongodb',
	'mysql-async',
	'oxmysql',
	'vSQL',
	'tg_prophunt',


}

-- Resources ที่ไม่ต้องการให้ PROTECT+ เข้าไปยุ่งเลย (ระบบจะไม่ฉีดไฟล์เข้าไปยุ่งกับ Resource นั้นๆ)
-- สำคัญ!!	หากใส่ชื่อ Resource ใดๆไว้ในนี้ PROTECT+ จะมองว่า Resource นั้นๆอยู่นอกเหนือการควบคุมของ PROTECT+ (ทุกอย่าง)
Config['AbsolutelyIgnoredAndNotInjectAnyFilesToResources / ไม่ให้ PROTECT+ ไปยุ่งอะไรเลย!'] = {
	-- ใส่ชื่อทรัพยากรที่นี่
	'connectqueue',
	'cc_ammosystem',
	'mk_weapon_lv',
	'ck_weapon_punk',
	'cc_weapon_t',
	'cc_weapon_r',
	'cc_weapon_punk',
	'cc_test_Candy',
	'cc_taser_clone',
	'cc_stungun',
	'cc_revolver',
	'cc_pumpshotgun',
	'cc_poolcue',
	'cc_hammer_np',
	'cc_gadgetpistol_clone',
	'cc_damage',
	'cc_bottle_sos',
	'cc_bottle_np',
	'cc_armor',
	'cc_bat1h_golf1h',
	'cc_armor',
	'xzero_giveui',
	'cc_megaphone',
	'pma-voice',
	'rp-radio',
	'x-radiolist',
	'heli',
	'okokTuning',
	'realisticvehicle',
	'esx-kr-vehicle-push',
	'CarHud',
	'cc_useallmeal',
	'cc_usebeer',
	'cc_useramen',
	'ws_selectmap',
	'w_hammergod',
	'rabbit_emotes_ui',
	'PolyZone',
	'ocrp_postal_map',
	'noidlecam',
	'nc_musicplayers',
	'nc_musicplayers_props',
	'lesslethal_shotgun',
	'helpnotify',
	'eco_anim',
	'cc_uicard_gang',
	'cc_uicard',
	'cc_uiairdrop_gang',
	'cc_uiairdrop',
	'cc_training',
	'cc_sound',
	'cc_snowballs',
	'cc_savezone',
	'cc_mysteryroom',
	'cc_mysmarket',
	'cc_changesurname',
	'cc_bounty',
	'cc_blip',
	'cc_blessingbell',
	'anchorboats',
	'an_killfeed',
	'cc_allportal',
	'Porpy_policealert',
	'cc_tablet',
	'cc_curfew',
	'cc_alertui',
	'cc_quest',
	'tc_propicecream',
	'cc_prisongps',
	'cc_jail',
	'pNotify',
	'PorNotify',
	'tops_warzone_circle',
	'Minimap-Bip',
	'gmap_afkv1_base',
	'cfx-nteam-legion-square-extended',
	'cfx-nteam-fleeca',
	'cc_props_postbox2',
	'cc_props_phone',
	'cc_props_duck',
	'cc_props_789store',
	'cc_prop_trashcan',
	'cc_prop_medical_bin',
	'cc_prop_market',
	'cc_mechanic',
	'cc_map_trunk',
	'cc_map_tents',
	'cc_map_superstore',
	'cc_map_illegalbox',
	'cc_map_garage',
	'cc_mailbox',
	'cc_house_robbery',
	'cc_garagetrunk_map',
	'cc_gachapon_map',
	'cc_eco_prop',
	'bob74_ipl',
	'Bahama_Mamas',
	'cc_amp_map',
	'cc_autofarm_map',
	'sandysheriff',
	'cc_icecreamshop_map',
	'gabzmrpd',
	'tg_krathong',
	'esx_identity',
	'cc_authlogin',
	'cc_weight',
	'esx_service',
	'DevilHunter_Hud',
	'xscoreboard',
	'crouch',
	'dpclothing',
	'dpemotes',
	'KL_Injury',
	'xsound',
	'notifyPhone',
	'esx_rpchat',
	'esx_addons_gcphone',
	'tg_fashionuse',
	'notz_boost_discord',
	'cc_xmas_babyqueen_2023',
	'cc_sweetshop_summersocute',
	'cc_sweetshop_baby',
	'cc_space_pup',
	'cc_hw_babyqueen_2023',
	'nc_squad',
	'cc_checkidentify',
	'autofarm_ui',
	'process_ui',
	'cc_coreeffect_ui',
	'cc_body',
	'cc_clothesall',
	'generic_texture_renderer_gfx',
	'interact-sound',
	'um-prop',
	'scotty-casino-baccarat-props',
	'holdem_props',
	'carsounds',
	'cc_circle_vehicle',
	'cc_medic_emsstalker',
	'cc_mediccar',
	'cc_normalcar',
	'cc_police_dominator',
	'cc_police_polbuffalor',
	'cc_police_polcoquettar2',
	'cc_police_polcoquettes2',
	'cc_police_polfmjs',
	'cc_police_polgresleyr',
	'cc_police_polvigeror',
	'cc_policecar',
	'cc_purgecar',
	'pd-safe',
	'lockpick',
	'cc_revolver_mk2',
	'sky_effect_emdiablo',
	'sky_weapon_emdiablo',
	'cc_props_songkran',
	'cc_poltrophytruck',
	'cc_map_evidence',
	'cc_prop_bjob',
	'cc_bmwm4mpl',
	'cc_slr34pl',
	'cc_agent_weapon',
	'cc_revolver_addon',
}