--[[
    ================== เริ่มต้นพื้นฐาน ==================
    ** weight 1 = 1 กิโลกรัม | สามารถกำหนด 0.50 หรือ 0.01 ได้ **
    -- weight = น้ำหนัก            (0  = ไม่มีน้ำหนัก)
    -- limit = จำนวนไอเทมที่เก็บได้  (-1 = ไม่จำกัดจำนวน)
]]
Config.Item_Info_Weight_Default     = 0.10  -- ค่าเริ่มต้นของไอเทม
Config.Item_Info_Limit_Default      = -1    -- ค่าเริ่มต้นของจำกัดจำนวนไอเทม (-1 = ไม่จำกัดจำนวน)
Config.Item_Info_Cal                = 1  -- หากใช้ประเป๋าประชารัชให้ปรับเป็น 1

--[[
    ================== ตั้งค่าไอเทม ==================
     ** weight 1 = 1 กิโลกรัม | สามารถกำหนด 0.50 หรือ 0.01 ได้ **
    weight = น้ำหนัก            (0  = ไม่มีน้ำหนัก)
    limit = จำนวนไอเทมที่เก็บได้  (-1 = ไม่จำกัดจำนวน)
]]

Config.Item_Info = { -- ตั้งค่าน้ำหนักไอเทมในหลังรถ
    ['medkit_pd'] = {weight = 0.1, limit = -1},

    ['medkit_md'] = {weight = 0.0, limit = -1},
    ['ginseng_md'] = {weight = 0.5, limit = -1},
    ['bandage'] = {weight = 0.1, limit = -1},

    ['painkiller'] = {weight = 0.1, limit = -1},
    ['blacksmith_box'] = {weight = 0.0, limit = -1},
    ['coin_blacksmith'] = {weight = 0.0, limit = -1},
    ['secret_box'] = {weight = 0.0, limit = -1},
    ['aed'] = {weight = 0.1, limit = -1},

    ['gov_toolkit'] = {weight = 0.1, limit = -1},

    ['chicken'] = {weight = 0.5, limit = -1},
    ['egg'] = {weight = 0.0, limit = -1},
    ['chicken_pro_1'] = {weight = 0.5, limit = -1},
    ['chicken_pro_2'] = {weight = 0.2, limit = -1},
    ['chicken_pack_1'] = {weight = 1.0, limit = -1},

    ['pork'] = {weight = 0.5, limit = -1},
    ['pork_pro_1'] = {weight = 0.5, limit = -1},
    ['pork_pro_2'] = {weight = 0.2, limit = -1},
    ['pork_pack_1'] = {weight = 1.0, limit = -1},

    ['rice'] = {weight = 0.5, limit = -1},
    ['rice_pro_1'] = {weight = 0.5, limit = -1},
    ['rice_pack_1'] = {weight = 1.0, limit = -1},

    ['coconut'] = {weight = 0.5, limit = -1},
    ['coconut_pro_1'] = {weight = 0.5, limit = -1},
    ['coconut_pack_1'] = {weight = 1.0, limit = -1},

    ['wood'] = {weight = 0.5, limit = -1},
    ['wood_pro_1'] = {weight = 0.5, limit = -1},
    ['wood_pro_2'] = {weight = 0.2, limit = -1},
    ['wood_pro_3'] = {weight = 0.1, limit = -1},
    ['wood_pro_4'] = {weight = 0.1, limit = -1},
    ['wood_pack_1'] = {weight = 0.5, limit = -1},

    ['fish_mullet'] = {weight = 0.5, limit = -1},
    ['fish_tilapia'] = {weight = 1.0, limit = -1},
    ['fish_snapper'] = {weight = 1.0, limit = -1},
    ['fish_can'] = {weight = 0.1, limit = -1},
    ['fish_bottle'] = {weight = 0.5, limit = -1},

    ['squid_1'] = {weight = 1.0, limit = -1},
    ['squid_2'] = {weight = 1.0, limit = -1},
    ['squid_3'] = {weight = 1.5, limit = -1},
    ['squid_4'] = {weight = 0.5, limit = -1},
    ['squid_ink'] = {weight = 0.1, limit = -1},

    ['black_money'] = {weight = 0.0, limit = -1},
    ['Phone'] = {weight = 0.0, limit = -1},
    ['body_bag'] = {weight = 0.0, limit = -1},
    ['icecream'] = {weight = 0.1, limit = -1},
    ['ticket_bm_1k'] = {weight = 0.0, limit = -1},
    ['ticket_bm_10k'] = {weight = 0.0, limit = -1},
    ['ticket_bm_100k'] = {weight = 0.0, limit = -1},
    ['cheque_1k'] = {weight = 0.0, limit = -1},
    ['cheque_10k'] = {weight = 0.0, limit = -1},
    ['cheque_100k'] = {weight = 0.0, limit = -1},
    
    ['condiment'] = {weight = 0.1, limit = -1},
    ['cookie'] = {weight = 0.2, limit = -1},
    ['meal_1'] = {weight = 1.0, limit = -1},
    ['meal_2'] = {weight = 1.0, limit = -1},
    ['meal_3'] = {weight = 1.0, limit = -1},
    ['ramen'] = {weight = 1.0, limit = -1},
    ['cookie'] = {weight = 0.2, limit = -1},
    ['meal_admin'] = {weight = 0, limit = -1},

    ['steel'] = {weight = 0.5, limit = -1},
    ['steel_pro_1'] = {weight = 0.02, limit = -1},
    ['steel_pro_2'] = {weight = 0.02, limit = -1},
    ['steel_pro_3'] = {weight = 0.1, limit = -1},

    ['stone'] = {weight = 0.5, limit = -1},
    ['stone_pro_1'] = {weight = 0.5, limit = -1},
    ['stone_pro_2'] = {weight = 0.2, limit = -1},
    ['stone_pro_3'] = {weight = 0.2, limit = -1},
    ['stone_pack_1'] = {weight = 0.1, limit = -1},

    ['ore'] = {weight = 0.2, limit = -1},
    ['ore_pro_1'] = {weight = 0.2, limit = -1},
    ['ore_pro_2'] = {weight = 0.2, limit = -1},
    ['ore_pro_3'] = {weight = 0.2, limit = -1},

    ['chilli'] = {weight = 0.1, limit = -1},
    ['basil'] = {weight = 0.1, limit = -1},
    ['ginseng'] = {weight = 0.1, limit = -1},
    ['guseng'] = {weight = 0.1, limit = -1},

    ['bonus_t'] = {weight = 0.0, limit = -1},
    ['bonus_h'] = {weight = 0.0, limit = -1},
    ['bonus_e'] = {weight = 0.0, limit = -1},
    ['bonus_c'] = {weight = 0.0, limit = -1},
    ['bonus_i'] = {weight = 0.0, limit = -1},
    ['bonus_r'] = {weight = 0.0, limit = -1},
    ['bonus_l'] = {weight = 0.0, limit = -1},
    ['lucky_box'] = {weight = 0.0, limit = -1},

    ['cement'] = {weight = 0.01, limit = -1},
    ['weed'] = {weight = 0.5, limit = -1},
    ['weed_pack'] = {weight = 1.0, limit = -1},
    ['cocaine'] = {weight = 0.5, limit = -1},
    ['cocaine_pack'] = {weight = 1.0, limit = -1},

    ['ink_well'] = {weight = 0.2, limit = -1},
    ['scuba'] = {weight = 0.2, limit = -1},
    ['toolkit'] = {weight = 0.1, limit = -1},
    ['weapon_box'] = {weight = 0.0, limit = -1},
    ['chromium'] = {weight = 0.0, limit = -1},
    ['platinum'] = {weight = 0.0, limit = -1},
    ['alloy'] = {weight = 0.5, limit = -1},
    ['paper'] = {weight = 0.1, limit = -1},
    ['lockpick'] = {weight = 0.1, limit = -1},

    ['eto'] = {weight = 0.1, limit = -1},
    ['pangtor'] = {weight = 0.1, limit = -1},
    ['sickle'] = {weight = 0.1, limit = -1},
    ['kukri'] = {weight = 0.1, limit = -1},
    ['axe'] = {weight = 0.1, limit = -1},
    ['fishing_rod'] = {weight = 0.1, limit = -1},
    ['fishing_bait'] = {weight = 0.01, limit = -1},
    ['welder'] = {weight = 0.1, limit = -1},
    ['pickaxe'] = {weight = 0.1, limit = -1},
    ['hammer'] = {weight = 0.1, limit = -1},
    ['scissor'] = {weight = 0.1, limit = -1},
    ['light_bulb'] = {weight = 1.0, limit = -1},
    ['adv_fishing_rod'] = {weight = 0.1, limit = -1},
    
    ['meth'] = {weight = 0.5, limit = -1},
    ['meth_a'] = {weight = 1.0, limit = -1},
    ['amp_r'] = {weight = 0.1, limit = -1},
    ['amp_b'] = {weight = 0.1, limit = -1},
    ['meth_b'] = {weight = 1.0, limit = -1},
    ['heroine'] = {weight = 1.0, limit = -1},
    ['super_aed'] = {weight = 0.1, limit = -1},
    ['busker'] = {weight = 0.0, limit = -1},
    ['event_box'] = {weight = 0.0, limit = -1},

    ['quest_a'] = {weight = 0.0, limit = -1},
    ['quest_b'] = {weight = 0.0, limit = -1},
    ['key_skull'] = {weight = 0.0, limit = -1},

    ['card_lastname'] = {weight = 0.0, limit = -1},
    ['auto_farm'] = {weight = 0.0, limit = -1},
    ['unlimit_bag'] = {weight = 0.0, limit = -1},
    ['meal_mre'] = {weight = 0.0, limit = -1},
    ['gum_mining'] = {weight = 0.0, limit = -1},

    ['cement_h'] = {weight = 0.1, limit = -1},
    ['peanut'] = {weight = 1.0, limit = -1},
    ['auto_1h'] = {weight = 0.0, limit = -1},
    ['gum_eco'] = {weight = 0.0, limit = -1},

    ['card_merchant_1'] = {weight = 0.0, limit = -1},
    ['card_merchant_2'] = {weight = 0.0, limit = -1},
    ['card_merchant_3'] = {weight = 0.0, limit = -1},
    ['card_merchant_4'] = {weight = 0.0, limit = -1},

    ['w1_gachapon'] = {weight = 0.0, limit = -1},
    ['w1_money'] = {weight = 0.0, limit = -1},
    ['w1_economy'] = {weight = 0.0, limit = -1},
    ['w1_material'] = {weight = 0.0, limit = -1},
    ['w1_ticket'] = {weight = 0.0, limit = -1},
    ['w1_illegal'] = {weight = 0.0, limit = -1},
    ['w1_mix'] = {weight = 0.0, limit = -1},
    ['w1_weapon'] = {weight = 0.0, limit = -1},
    ['w1_special'] = {weight = 0.0, limit = -1},
    ['cube_black'] = {weight = 0.0, limit = -1},
    ['cube_red'] = {weight = 0.0, limit = -1},

    ['skateboard'] = {weight = 0.0, limit = -1},

    ['chromate'] = {weight = 0.0, limit = -1},
    ['vest_50'] = {weight = 0.1, limit = -1},
    ['vest_100'] = {weight = 0.1, limit = -1},

    ['old_compass'] = {weight = 0.0, limit = -1},
    ['old_cup'] = {weight = 0.0, limit = -1},
    ['old_lamp'] = {weight = 0.0, limit = -1},
    ['old_anvil'] = {weight = 0.0, limit = -1},
    ['old_book'] = {weight = 0.0, limit = -1},

    ['letter'] = {weight = 0.1, limit = -1},
    ['screwdv'] = {weight = 0.1, limit = -1},
    ['screwdv_broken'] = {weight = 0.1, limit = -1},

    ['auto_board'] = {weight = 0.1, limit = -1},
    ['weapon_box_f'] = {weight = 0.1, limit = -1},

    ['cart_merchant_1'] = {weight = 0.0, limit = -1},
    ['cart_merchant_2'] = {weight = 0.0, limit = -1},
    ['cart_merchant_3'] = {weight = 0.0, limit = -1},
    ['cart_merchant_4'] = {weight = 0.0, limit = -1},
    ['drug_skull'] = {weight = 1.0, limit = -1},
    ['amp_g'] = {weight = 0.1, limit = -1},

    ['starter_kit'] = {weight = 0.0, limit = -1},
    ['ticket_bmarket'] = {weight = 0.0, limit = -1},
    ['box_gold'] = {weight = 0.0, limit = -1},
    ['box_steel'] = {weight = 0.0, limit = -1},
    ['box_copper'] = {weight = 0.0, limit = -1},
    ['box_wood'] = {weight = 0.0, limit = -1},
    ['adrenaline'] = {weight = 0.5, limit = -1},
    ['coin_mystery'] = {weight = 0.0, limit = -1},
    ['coffin'] = {weight = 0.5, limit = -1},
    ['blood'] = {weight = 0.1, limit = -1},
    ['fang'] = {weight = 0.0, limit = -1},
    ['card_thief_1'] = {weight = 0.0, limit = -1},
    ['card_thief_2'] = {weight = 0.0, limit = -1},
    ['card_thief_3'] = {weight = 0.0, limit = -1},
    ['card_thief_4'] = {weight = 0.0, limit = -1},
    ['box_coin_bsmith'] = {weight = 0.0, limit = -1},
    ['box_b_weapon'] = {weight = 0.0, limit = -1},
    ['box_chromate'] = {weight = 0.0, limit = -1},
    ['cc_blessing'] = {weight = 0.0, limit = -1},
    ['gov_tracker'] = {weight = 0.1, limit = -1},
    ['cc_clipper'] = {weight = 0.0, limit = -1},
    ['gov_tablet'] = {weight = 0.0, limit = -1},
    ['gov_coffin'] = {weight = 0.0, limit = -1},
    ['gov_skeleton'] = {weight = 0.0, limit = -1},
    ['gov_flag'] = {weight = 0.0, limit = -1},
    ['card_illegal_3d'] = {weight = 0.0, limit = -1},
    ['casino_chip'] = {weight = 0.0, limit = -1},
    ['gov_bag'] = {weight = 0.0, limit = -1},
    ['vault_kit'] = {weight = 0.0, limit = -1},
    ['beginner_box'] = {weight = 0.0, limit = -1},
    ['fashion_box_w1'] = {weight = 0.0, limit = -1},
    ['meow_rabbit3_halloween2023'] = {weight = 0.0, limit = -1},
    ['meow_rabbit2_halloween2023'] = {weight = 0.0, limit = -1},
    ['meow_rabbit_halloween2023'] = {weight = 0.0, limit = -1},
    ['meow_hwcat3'] = {weight = 0.0, limit = -1},
    ['meow_hwcat2'] = {weight = 0.0, limit = -1},
    ['meow_hwcat1'] = {weight = 0.0, limit = -1},
    ['meow_hw3_soullantern'] = {weight = 0.0, limit = -1},
    ['meow_hw3_shoe2'] = {weight = 0.0, limit = -1},
    ['meow_hw3_shoe1'] = {weight = 0.0, limit = -1},
    ['meow_hw3_pot'] = {weight = 0.0, limit = -1},
    ['meow_hw3_batpum'] = {weight = 0.0, limit = -1},
    ['helloween3'] = {weight = 0.0, limit = -1},
    ['helloween2'] = {weight = 0.0, limit = -1},
    ['helloween1'] = {weight = 0.0, limit = -1},
    ['meow_hw_coffin2'] = {weight = 0.0, limit = -1},
    ['farming_bag_2h'] = {weight = 0.0, limit = -1},
    ['beginner_car'] = {weight = 0.0, limit = -1},
    ['gov_medal'] = {weight = 0.0, limit = -1},
    ['weapon_box_unt'] = {weight = 0.0, limit = -1},
    ['box_cement'] = {weight = 0.0, limit = -1},
    ['bonus_broken'] = {weight = 0.0, limit = -1},
    ['gov_holiday'] = {weight = 0.0, limit = -1},
    ['citizen_coin'] = {weight = 0.0, limit = -1},
    ['veh_towel'] = {weight = 0.0, limit = -1},
    ['mushroom'] = {weight = 0.2, limit = -1},
    ['pangtor_2'] = {weight = 0.0, limit = -1},
    ['eto_2'] = {weight = 0.0, limit = -1},
    ['kukri_2'] = {weight = 0.0, limit = -1},
    ['sickle_2'] = {weight = 0.0, limit = -1},
    ['axe_2'] = {weight = 0.0, limit = -1},
    ['pangtor_2b'] = {weight = 0.0, limit = -1},
    ['eto_2b'] = {weight = 0.0, limit = -1},
    ['kukri_2b'] = {weight = 0.0, limit = -1},
    ['sickle_2b'] = {weight = 0.0, limit = -1},
    ['axe_2b'] = {weight = 0.0, limit = -1},
    ['blessing_bell'] = {weight = 0.0, limit = -1},
    ['piggy_bank'] = {weight = 0.0, limit = -1},
    ['money_coin'] = {weight = 0.0, limit = -1},
    ['eco_coin'] = {weight = 0.0, limit = -1},
    ['material_coin'] = {weight = 0.0, limit = -1},
    ['ticket_coin'] = {weight = 0.0, limit = -1},
    ['illegal_coin'] = {weight = 0.0, limit = -1},
    ['mix_coin'] = {weight = 0.0, limit = -1},
    ['weapon_coin'] = {weight = 0.0, limit = -1},
    ['special_coin'] = {weight = 0.0, limit = -1},
    ['keycard_silver'] = {weight = 0.1, limit = -1},
    ['keycard_gold'] = {weight = 0.1, limit = -1},
    ['keycard_red'] = {weight = 0.1, limit = -1},
    ['disruptor'] = {weight = 0.1, limit = -1},
    ['armory_box'] = {weight = 0.0, limit = -1},
}

Config.Item_BlackList_Name = { -- BlackList ไอเทมที่จะไม่ให้เก็บในหลังรถ
    "key_pd",
    "key_boss_pd",

    "key_md",
    "key_boss_md",
    "key_vice_md",

    "key_cc",
    "card_gang",
    "coin_circle",

    "radio",
    "gov_scuba",
    "gov_vest",

    "money",
    "player_mask",
    "card_id",
    "card_nplayer",
    "card_trade",
    "card_vault",
    
    "key_master",
    "super_bag",

    "5kg_bag",
    
    "card_reskin",

    "coin_unlucky",
    "key_vault",

    "coin_gang",

    "bp_wrench",
    "bp_bat",
    "bp_golfclub",
    "bp_knuckle",
    "bp_machete",
    "bp_bottle",
    "bp_battleaxe",
    "bp_knife",
    "bp_dagger",
    "bp_poolcue",
    "bp_hammer",

    "pt_wrench",
    "pt_bat",
    "pt_golfclub",
    "pt_knuckle",
    "pt_machete",
    "pt_bottle",
    "pt_battleaxe",
    "pt_knife",
    "pt_dagger",
    "pt_poolcue",
    "pt_hammer",
    "pt_revolver",

    "WEAPON_WRENCH",
    "WEAPON_POOLCUE",
    "WEAPON_BAT_1H",
    "WEAPON_GOLFCLUB_1H",
    "WEAPON_KNUCKLE",
    "WEAPON_MACHETE",
    "WEAPON_BOTTLE",
    "WEAPON_BATTLEAXE",
    "WEAPON_KNIFE",
    "WEAPON_DAGGER",
    "WEAPON_POOLCUE_B",
    "WEAPON_POOLCUE_G",

    "WEAPON_STUNGUN",
    "WEAPON_PUMPSHOTGUN",
    "WEAPON_NIGHTSTICK",
    "WEAPON_PISTOL_MK2",
    "WEAPON_TACTICALRIFLE",
    "WEAPON_SWITCHBLADE",

    "WEAPON_PETROLCAN",
    "WEAPON_HAMMER_NP",
    "WEAPON_BOTTLE_NP",
    "WEAPON_BOTTLE_SOS",
    "gadget_parachute",

    "busker",
    "event_box",

    "quest_a",
    "quest_b",
    "key_skull",

    "card_lastname",
    "auto_farm",
    "unlimit_bag",
    --"meal_mre",
    "gum_mining",

    "auto_1h",
    "gum_eco",

    "card_merchant_1",
    "card_merchant_2",
    "card_merchant_3",
    "card_merchant_4",

    "ticket_eco_x2",

    "painkiller",
    "vest_50",
    "vest_100",

    "cart_merchant_1",
    "cart_merchant_2",
    "cart_merchant_3",
    "cart_merchant_4",

    "starter_kit",
    "WEAPON_CROWBAR",
    "coin_mystery",

    "card_thief_1",
    "card_thief_2",
    "card_thief_3",
    "card_thief_4",

    "cc_blessing",
    "gov_tracker",
    "cc_clipper",
    "gov_tablet",
    "gov_coffin",
    "gov_skeleton",
    "gov_flag",
    "card_illegal_3d",
    "casino_chip",
    "gov_bag",
    "beginner_box",
    "fashion_box_w1",
    "meow_rabbit3_halloween2023",
    "meow_rabbit2_halloween2023",
    "meow_rabbit_halloween2023",
    "meow_hwcat3",
    "meow_hwcat2",
    "meow_hwcat1",
    "meow_hw3_soullantern",
    "meow_hw3_shoe2",
    "meow_hw3_shoe1",
    "meow_hw3_pot",
    "meow_hw3_batpum",
    "helloween3",
    "helloween2",
    "helloween1",
    "meow_hw_coffin2",
    "farming_bag_2h",
    "beginner_car",
    "gov_medal",
    "fang",
    "skateboard",
    "weapon_box_unt",
    "bonus_broken",
    "gov_holiday",
    "citizen_coin",
    "blessing_bell",
    "armory_box",
    "piggy_bank",
    "money_coin",
    "eco_coin",
    "material_coin",
    "ticket_coin",
    "illegal_coin",
    "mix_coin",
    "weapon_coin",
    "special_coin",
    "WEAPON_BOTTLE_PUNK",
    "WEAPON_POOLCUE_PUNK",
    "WEAPON_BAT_PUNK",
    "WEAPON_GOLFCLUB_PUNK",
    "WEAPON_MACHETE_PUNK",
    "WEAPON_KNIFE_PUNK",
    "WEAPON_HAMMER_PUNK",
	"WEAPON_KNUCKLE_PUNK",
	"WEAPON_DAGGER_PUNK",
    "WEAPON_REVOLVER",
}