-- ████╗   ██╗   ██████╗   ██████╗  ██████╗ ██╗  ██╗ ██████╗ ██╗     █████╗  ██████╗  ██████╗ ██████╗    ██╗ --
-- ██╔██╗  ██║ ██╔═════╝   ██╔══██╗ ██╔═══╝ ██║  ██║ ██╔═══╝ ██║    ██╔══██╗ ██╔══██╗ ██╔═══╝ ██╔══██╗   ██║ --
-- ██║╚██╗ ██║ ██║         ██║  ██║ █████╗  ██║  ██║ █████╗  ██║    ██║  ██║ ██████╔╝ █████╗  ██████╔╝   ██║ --
-- ██║ ╚██╗██║ ██║         ██║  ██║ ██╔══╝  ╚██╗██╔╝ ██╔══╝  ██║    ██║  ██║ ██╔═══╝  ██╔══╝  ██╔══██╗   ╚═╝ --
-- ██║  ╚████║ ╚═██████╗   ██████╔╝ ██████╗  ╚███╔╝  ██████╗ ██████╗╚█████╔╝ ██║      ██████╗ ██║  ██║   ██╗ --
-- ╚═╝   ╚═══╝   ╚═════╝   ╚═════╝  ╚═════╝   ╚══╝   ╚═════╝ ╚═════╝ ╚════╝  ╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝ --

-- น้ำหนักของสิ่งของชนิดต่างๆต่อ 1 ชิ้น (หน่วยเป็น Kg) ** หากไม่ใส่ จะอิงตามน้ำหนักในระบบ es_extended หรือเบสอื่นๆ
Config.ItemsWeight = {
	-- ['bread'] = 500,
	-- ['water'] = 500,
}

-- Limit ของสิ่งของชนิดต่างๆ ** หากไม่ใส่ จะอิงตาม Limit ในระบบ es_extended หรือเบสอื่นๆ
Config.ItemsLimit = {
	-- ['bread'] = 5,
	-- ['water'] = 5,
	['helmet'] = 3,
}

-- ความหายากของสิ่งของชนิดต่างๆ ** หากไม่ใส่ จะอิงตาม Rarity ในระบบ es_extended หรือเบสอื่นๆ
Config.ItemsRarity = {
	['card_reskin'] = 5,
	['card_lastname'] = 5,
	['auto_1h'] = 5,
	['gum_mining'] = 5,
	['gum_eco'] = 5,
	['card_vip'] = 5,
	['card_vault'] = 5,
	['exp_vault'] = 4,
	['cron'] = 5,
	['heart_100'] = 4,
	['rental_3d'] = 5,
	['rental_7d'] = 5,
	['rental_15d'] = 5,
	['gacha_5'] = 5,
	['gacha_5_1'] = 5,
	['gacha_5_2'] = 5,
	['gacha_5_3'] = 5,
	['gacha_5_4'] = 5,
	['ad_blessing'] = 5,
	['ad_bell'] = 5,
	['ad_clipper'] = 5,
	['ad_spray'] = 5,
	['vault_master'] = 5,
	['ad_bag'] = 5,
	['busker'] = 5,
	['starter_kit'] = 4,
	['box_rcar'] = 4,
	['gacha_support'] = 5,
	['sulfur'] = 2,
	['steel_3'] = 3,
	['coal'] = 2,
	['bonus_eco'] = 4,
	['bonus_mining'] = 4,
	['vault_md'] = 6,
	['medkit'] = 6,
	['vault_pd'] = 6,
	['megaphone'] = 6,
	['coin_killer'] = 5,
	['gov_toolkit'] = 6,
	['gov_aed'] = 6,
	['gov_radio'] = 6,
	['gov_scuba'] = 6,
	['gov_vest'] = 6,
	['gov_tablet'] = 6,
	['pt_all'] = 4,
	['t1_box_knuckle'] = 6,
	['t1_box_machete'] = 6,
	['t1_box_bottle'] = 6,
	['t1_box_poolcue'] = 6,
	['t1_player'] = 6,
	['cement'] = 2,
	['amp_r'] = 2,
	['amp_b'] = 2,
	['amp_g'] = 3,
	['keycard_silver'] = 3,
	['keycard_gold'] = 4,
	['keycard_red'] = 5,
	['house_silver'] = 3,
	['house_gold'] = 4,
	['house_red'] = 5,
	['cocaine_1'] = 1,
	['cocaine_2'] = 2,
	['meth'] = 1,
	['meth_a'] = 2,
	['meth_b'] = 3,
	['heroine'] = 4,
	['exp_gang'] = 5,
	['key_gang'] = 4,
	['gun_pin'] = 3,
	['gun_barrel'] = 3,
	['gun_spring'] = 3,
	['revolver_1'] = 4,
	['revolver_2'] = 4,
	['revolver_3'] = 4,
	['alloy'] = 4,
	['heart_70'] = 2,
	['heart_90'] = 3,
	['exp'] = 4,
	['meal_mre'] = 4,
	['r_bandage'] = 6,
	['r_painkiller'] = 6,
	['r_adrenaline'] = 6,
	['r_vest'] = 6,
	['r_aed'] = 6,
	['gacha_event'] = 4,
	['fashion_0'] = 4,
	['gov_help'] = 6,
	['tag_gang'] = 4,
	['gov_painkiller'] = 6,
	['box_exp'] = 5,
	['box_amp'] = 3,
}

-- ปิดกระเป๋าเมื่อใช้งานสิ่งของต่างๆ
Config.CloseInventoryOnUseItem = {
	-- 'bread',
	-- 'water',
}

-- ปิดกระเป๋าเมื่อทิ้งสิ่งของต่างๆ
Config.CloseInventoryOnDropItem = {
	-- 'bread',
	-- 'water',
}

-- สิ่งของที่ต้องการให้เก็บอาวุธก่อนแล้วจึงใช้งาน
Config.PocketWeaponWhenUse = {
	-- 'bread',
	-- 'water',
}

-- Blacklist ทิ้งของ/มอบของ
Config.ItemsActionList = {
	shortcut = {				-- การ Item ของเข้า Shortcuts
		type = 'blacklist',		-- ชนิดของ List ที่ต้องการ (whitelist|blacklist)
		list = {
			-- 'bread',
			-- 'water',
		}
	},
	use = {						-- การ "ใช้" สิ่งของต่างๆ
		type = 'blacklist',
		list = {
			-- 'meal_mre',
			-- 'booster1',
			-- 'booster2',
			-- 'booster3',
		}
	},
	drop = {					-- การ "ทิ้ง" สิ่งของต่างๆ
		type = 'blacklist',
		list = {
			'card_reskin',
			'card_lastname',
			'auto_1h',
			'gum_mining',
			'gum_eco',
			'card_vip',
			'cron',
			'heart_100',
			'ad_blessing',
			'ad_clipper',
			'ad_spray',
			'vault_master',
			'ad_bag',
			'busker',
			'starter_kit',
			'box_rcar',
			'gacha_support',
			'vault_md',
			'vault_pd',
			'card_gang',
			'megaphone',
			'r_bandage',
			'r_painkiller',
			'r_vest',
			'r_aed',
			't1_box_knuckle',
			't1_box_machete',
			't1_box_bottle',
			't1_box_poolcue',
			't1_player',
			'card_nplayer',
			'vault_key',
			'quest_a',
			'quest_b',
			'exp',
			'key_gang',
			'gacha_5',
			'gacha_5_1',
			'gacha_5_2',
			'gacha_5_3',
			'gacha_5_4',
			'exp_gang',
			'house_silver',
			'house_gold',
			'house_red',
			'rental_3d',
			'rental_7d',
			'rental_15d',
			'coin_killer',
			'r_adrenaline',
			'player_mask',
			'card_id',
			'card_family',
			'card_vault',
			'exp_vault',
			'ad_bell',
			'gacha_event',
			'fashion_0',
			'baby1',
			'baby2',
			'baby3',
			'baby4',
			'baby5',
			'baby6',
			'baby7',
			'baby8',
			'spacpup',
			'spacpupb',
			'spacpupc',
			'spacpupd',
			'spacpupe',
			'spacpupf',
			'summersocute1',
			'summersocute2',
			'summersocute3',
			'summersocute4',
			'summersocute5',
			'summersocute6',
			'booster1',
			'booster2',
			'booster3',
			'card_wvault',
			'box_ad_citizen',
			'box_ad_family',
			'box_ad_gang',
			'box_sa_citizen',
			'box_sa_family',
			'box_sa_gang',
			'box_exp',
		}
	},
	give = {					-- การ "มอบ" สิ่งของต่างๆ
		type = 'blacklist',
		list = {
			'card_reskin',
			'card_lastname',
			'auto_1h',
			--'gum_mining',
			--'gum_eco',
			'card_vip',
			--'cron',
			--'heart_100',
			'ad_blessing',
			'ad_clipper',
			'ad_spray',
			'vault_master',
			'ad_bag',
			'busker',
			'starter_kit',
			'box_rcar',
			'gacha_support',
			'vault_md',
			'vault_pd',
			'card_gang',
			'pt_all',
			'r_bandage',
			'r_painkiller',
			'r_vest',
			'r_aed',
			't1_player',
			'skateboard',
			'snow_gloves',
			'hifi',
			'card_nplayer',
			'vault_key',
			'quest_a',
			'quest_b',
			'card_afk',
			--'exp',
			'weapon_box_unt',
			'key_gang',
			'exp_gang',
			'house_silver',
			'house_gold',
			'house_red',
			'rental_3d',
			'rental_7d',
			'rental_15d',
			'r_adrenaline',
			'player_mask',
			'card_id',
			'card_family',
			'card_vault',
			'exp_vault',
			'ad_bell',
			'gacha_event',
			'fashion_0',
			'booster1',
			'booster2',
			'booster3',
			'card_wvault',
			'box_exp',
		}
	},
	search = {					-- การ "โยกย้าย" สิ่งของต่างๆเมื่อเปิดกระเป๋าผู้เล่น
		type = 'blacklist',
		list = {
			'card_reskin',
			'card_lastname',
			'auto_1h',
			'gum_mining',
			'gum_eco',
			'card_vip',
			'cron',
			'heart_100',
			'ad_blessing',
			'ad_clipper',
			'ad_spray',
			'vault_master',
			'ad_bag',
			'starter_kit',
			'box_rcar',
			'gacha_support',
			--'vault_pd',
			'megaphone',
			'pt_all',
			'card_nplayer',
			'vault_key',
			'quest_a',
			'quest_b',
			'exp',
			'weapon_box_unt',
			'gacha_5',
			'gacha_5_1',
			'gacha_5_2',
			'gacha_5_3',
			'gacha_5_4',
			'exp_gang',
			'house_silver',
			'house_gold',
			'house_red',
			'rental_3d',
			'rental_7d',
			'rental_15d',
			'coin_killer',
			'player_mask',
			'card_id',
			'card_vault',
			'exp_vault',
			'ad_bell',
			'gacha_event',
			'fashion_0',
			'baby1',
			'baby2',
			'baby3',
			'baby4',
			'baby5',
			'baby6',
			'baby7',
			'baby8',
			'spacpup',
			'spacpupb',
			'spacpupc',
			'spacpupd',
			'spacpupe',
			'spacpupf',
			'summersocute1',
			'summersocute2',
			'summersocute3',
			'summersocute4',
			'summersocute5',
			'summersocute6',
			'booster1',
			'booster2',
			'booster3',
			'card_wvault',
			'box_ad_citizen',
			'box_ad_family',
			'box_ad_gang',
			'box_sa_citizen',
			'box_sa_family',
			'box_sa_gang',
			'box_exp',
		}
	}
}
-- การตั้งค่า Action ต่างๆ
-- 'whitelist'	=> Items ต่างๆที่อยู่ใน List จะ "อนุญาต" ให้ทำการกระทำนั้นๆ
--				=> โดยที่ Items ที่ไม่อยู่ใน List จะ "ไม่อนุญาต" ให้ทำการกระทำนั้นๆ
-- 'blacklist'	=> Items ต่างๆที่อยู่ใน List จะ "ไม่อนุญาต" ให้ทำการกระทำนั้นๆ
--				=> โดยที่ Items ที่ไม่อยู่ใน List จะ "อนุญาต" ให้ทำการกระทำนั้นๆ