fx_version 'cerulean'
game 'gta5'


files {
    "stream/*.ytyp",
    "stream/*.ydr",
    "stream/*.ytd",
}

data_file "DLC_ITYP_REQUEST" "stream/bukey.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/lx1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/lx2.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/lx3.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/lx4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/lx5.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/lx6.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/carebear1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/carebear2.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/carebear3.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/carebear4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/carebear5.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/carebear6.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/cat1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/cat2.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/cat3.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/cat4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/book1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/book2.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/polaroid.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/flower1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/hamster1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/hamster2.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/hamster3.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/hamster4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/krathong1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/krathong2.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/flowlantern1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/flowlantern2.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/flowlantern3.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/flowlantern4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/flowlantern5.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/duck_kt1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/duck_kt2.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/duck_kt3.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/duck_kt4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/duck_kt5.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/duck_kt6.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/duck_kt7.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/duck_kt8.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/mini1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/mini2.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/mini3.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/mini4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/mini5.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/mini6.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/mini7.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/mini8.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/tulip1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/tulip2.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/tulip3.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/tulip4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/tulip5.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/tulipbukey1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/tulipbukey2.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/tulipbukey3.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/tulipbukey4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/tulipbukey5.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/blackumbrella.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/babycm_prop1.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/babycm_prop2.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/babycm_prop3.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/babycm_prop4.ytyp"