fx_version 'cerulean'
game 'gta5'

client_script 'client/ptfx.lua'
client_script 'client/boost.lua'
client_script 'client/trails.lua'
client_script 'client/main.lua'
client_script 'client/purge.lua'
client_script 'config.lua'
server_script  '@oxmysql/lib/MySQL.lua'
server_script 'server/main.lua'
server_script 'config.lua'
